// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAplicationForServices.Server.Data;

#nullable disable

namespace WebAplicationForServices.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220201205445_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebAplicationForServices.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Az sum deskription 1 dasdasdasdasdsadasdasdasdasads",
                            ImageUrl = "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            Price = 1.2m,
                            Title = "Az sum produkt1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Az sum deskription 2 dasdasdasdasdsadasdasdasdasads",
                            ImageUrl = "https://napravisam.net/wp-content/uploads/1246.jpg",
                            Price = 1.2m,
                            Title = "Usluga - Kosene na treva"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Az sum deskription 3 dasdasdasdasdsadasdasdasdasads",
                            ImageUrl = "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            Price = 1.2m,
                            Title = "Az sum produkt3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
